apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
  labels:
    app: mosquitto
data:
  password.txt: |
    jeremie:$7$101$LsEZ2IufAZw1SW3k$1B7AkeyNpHQerQ7W1O1flaAFsZBW0PozaZJkjaSdVLa+HMcIbbhVapGVuaKq29cusR7p6xjbnU6Vul9vzFH+aQ==

